### ISSUE TITLE
Unable to activate/view some scenes when this module is enabled

### ISSUE THREAD

**Issue by JamzTheMan** [velara/pf2edragruler#10]
The error points to terrain.js but the issue only persists if I enable this module. If I disable the module I can view the scene again without errors. I've added the scene exported if it helps (although I get other errors regarding texture width when I try and import this into another server)

[fvtt-Scene-The_Rusty_Dragon_Inn.zip](https://github.com/League-of-Foundry-Developers/pf2edragruler/files/6393490/fvtt-Scene-The_Rusty_Dragon_Inn.zip)

![image](https://user-images.githubusercontent.com/8051654/116442137-c489a000-a817-11eb-861d-70d58d26d17d.png)

**Comment by velara** [comment]
The only errors I'm getting are related to missing pngs. Although I'm using my development copy of the integration.

I suspect the issue is related to the changes that Ironmonk made to obstacles in the last update. Since my module makes an explicit call to the old obstacle function. I'm just about the upload the changes to make it compatible with the latest update. So hopefully when I finish putting out the patch this issue will resolve itself.

**Comment by velara** [comment]
Patch is live. When you get a chance, let me know if your issue persists.
