### ISSUE TITLE
Issue with FoundryVTT Arms Reach

### ISSUE THREAD

**Issue by KevinRichard-GM** [velara/pf2edragruler#23]
With FoundryVTT Arms Reach module enabled the drag ruler fails to color the measurement ruler when a token is dragged indicating 3 action economy movement phases. 

This appears to be an issue with other Drag Ruler Integrations (GURPS was mentioned) as a issue is open on the FoundryVTT Arms Reach module page. They are claiming it is not their module causing the issue and indicate this is the problem:

The "GURPSSpeedProvider" class on the file "gurps.js" file does not set a super constructor as described [here](https://github.com/p4535992/foundryvtt-arms-reach/issues/23#:~:text=The%20%22GURPSSpeedProvider%22%20class%20on%20the%20file%20%22gurps.js%22%20file%20does%20not%20set%20a%20super%20constructor%20as%20described%20here).

Including the error log from the console of my session as I use PF2E. It looks to be the same issue:

![image](https://user-images.githubusercontent.com/75590180/132989928-e89d26ad-e232-4da4-9fcd-a621de8c33e2.png)

Using the latest version of Edge, FoundryVTT 0.8.9, hosted on ForgeVTT and all modules involved are latest version as of 9/12/2021@09:43am.

**Comment by velara** [comment]
I’ve got no desire to dig into figuring out a fix for this independently. I’m not even entirely sure it’s fixable solely on my end without changing how drag ruler expects speed providers to be formatted. 

I’ll follow the issue on the drag ruler page and if there are updated guidelines for setting up integrations to resolve the conflict I’ll implement them. But otherwise the integration will remain incompatible with arms reach until either arms reach is updated to not trigger a conflict or drag ruler updates what it expects speed providers to look like.

**Comment by velara** [comment]
Was resolved by Drag Ruler
