### ISSUE TITLE
V10 deprecation warnings.

### ISSUE THREAD

**Issue by tehguitarist** [velara/pf2edragruler#42]
Nothing major, just some deprecation warnings for the module.json
<img width="1098" alt="Screenshot 2023-02-01 at 7 22 10 pm" src="https://user-images.githubusercontent.com/28495826/215990010-460802f4-6420-4ee0-a767-386455377d62.png">

**Comment by velara** [comment]
I think you ended up on the wrong page, this isn’t PF2e tokenmagic.

**Comment by tehguitarist** [comment]
Apologies @velara, wrong screenshot
<img width="1238" alt="Screenshot 2023-02-03 at 4 10 21 pm" src="https://user-images.githubusercontent.com/28495826/216517728-967f996d-6cf5-4db4-9ea6-6cd82498db89.png">

**Comment by velara** [comment]
You seem to be on an outdated version of the module, if you check the module.json on the main page you’ll see that all of those migrations have already been done. 

I can only assume it’s related to the issue with foundry’s versioning recently where it has been serving oldest compatible rather than newest compatible when folks are updating or downloading modules
