### ISSUE TITLE
enhanced terrain layer - aquatic/water

### ISSUE THREAD

**Issue by zarmstrong** [velara/pf2edragruler#8]
Useing ETL, the tile type "water" does not account for swimspeed, but "aquatic" does

**Comment by velara** [comment]
I haven't been able to reproduce this on my end. 

In my test world, with automatic movement switching on, both Water and Aquatic terrain switch the token to the swim speed. The main difference I'm seeing between the two is that Water difficult terrain is ignored (since the swim speed is being used) while Aquatic difficult terrain is not. 

![image](https://user-images.githubusercontent.com/74130268/113799962-57508680-9713-11eb-8fd7-fb4fe4b4cd39.png)
Water Difficult Terrain with a 5ft swim speed. 

![image](https://user-images.githubusercontent.com/74130268/113800033-74855500-9713-11eb-89a3-789345abfb2a.png)
Aquatic Difficult Terrain with a 5ft swim speed. 

As you can see in both cases the movement speed is successfully switching to 5ft per movement for me, and the aquatic difficult terrain is counting, while the water difficult terrain is being treated as normal terrain. 

Would you mind sending me your reproduction steps & the module version number and I'll see if I can't replicate the behaviour on my end so I can squash whatever bug is causing your issue.

**Comment by zarmstrong** [comment]
Things to even weirder when I tried to repro for you:

Created a new world with only these 3 modules:
![image](https://user-images.githubusercontent.com/565269/113807723-e8c6f500-9721-11eb-9071-78ba8a4ad141.png)

Map with aquatic (2x difficult), water (3x) and mountain (4x):
![image](https://user-images.githubusercontent.com/565269/113808734-dea5f600-9723-11eb-8dc5-a36bb14855f4.png)


Moving over aquatic (no swim speed)
![image](https://user-images.githubusercontent.com/565269/113808785-ff6e4b80-9723-11eb-8a17-4afa410d8713.png)

Moving over aquatic (swim speed is 10): 
![image](https://user-images.githubusercontent.com/565269/113808815-0dbc6780-9724-11eb-8f1d-ef497eb02aed.png)

Moving over water and mountain (swim speed 10): 
![image](https://user-images.githubusercontent.com/565269/113808844-1d3bb080-9724-11eb-9a59-07b9a32ddbbf.png)
![image](https://user-images.githubusercontent.com/565269/113808854-23319180-9724-11eb-8667-42177e795b68.png)


Seems like no difficult terrain is being triggered at all.

![image](https://user-images.githubusercontent.com/565269/113808917-45c3aa80-9724-11eb-8967-038811b75491.png)

**Comment by velara** [comment]
I can't speak to the original issue. However, for the ruler to detect difficult terrain, Terrain Ruler (https://foundryvtt.com/packages/terrain-ruler) is required. 

Which is why you're not seeing any effect of difficult terrain in your attempts to reproduce.

**Comment by zarmstrong** [comment]
*facepalm* 

Ok I'll repro with terrain ruler enabled

**Comment by zarmstrong** [comment]
Enabled terrain ruler, seeing the difficult terrain stuff now.

Settings, speed provider is module PF2e Drag Ruler Integration:
![image](https://user-images.githubusercontent.com/565269/113814245-8fb18e00-972e-11eb-841f-4e6051b800d9.png)

Same map as above, just changed water from 3x to 2x. PC has swim speed 10.
![image](https://user-images.githubusercontent.com/565269/113814401-d7381a00-972e-11eb-842e-e5468289d696.png)
![image](https://user-images.githubusercontent.com/565269/113814419-de5f2800-972e-11eb-8865-7f9af88274b3.png)

So it appears as though the transition from land to water doesn't account for swim speed from the above.

Now trying movement within the different terrains:
![image](https://user-images.githubusercontent.com/565269/113814548-10708a00-972f-11eb-9cbf-e7e2b5ff0322.png)
![image](https://user-images.githubusercontent.com/565269/113814586-1cf4e280-972f-11eb-89eb-958541390307.png)

I agree that it seems like aquatic is the issue, but water is not.   Maybe I misread what I had set in my normal game.  Either way, should aquatic be counted as water for the purposes of swim speed? I don't know why there's a differentiation between water and aquatic in ETL

**Comment by velara** [comment]
Ah, this is for the moment expected behaviour.

**_Regarding:_** "So it appears as though the transition from land to water doesn't account for swim speed from the above."

At present, mid-movement speed switching isn't supported. Which means the speed your token uses for the ruler is set by the square that your movement begins from. This is mostly due to technical limitations, as recalculating your movement speed after each square would have an adverse effect on performance. 

Which means until I find a performant solution to that problem the current behaviour is unfortunately likely to remain. 



**_Regarding:_**: "Now trying movement within the different terrains"

In this case your token is actually using your swim speed in both instances. With 10ft of movement representing one action worth of movement in both terrains. The reason for the discrepancy you're seeing in this instance is due to how I'm treating water vs aquatic difficult terrain. 

Aquatic difficult terrain is intended to represent water specific difficult terrain that would effect swimming creatures. For example: a current that is difficult to swim in. Which means that for your swimming creature each square will take 10 ft of movement, 5ft + 5ft for the difficult terrain.

In contrast, Water is intended to represent the difficulty of crossing through areas of water, but I wanted it to have no effect on swimming creatures. So you token in this instance treats each square as 5ft of movement due to ignoring the effects of the water being difficult terrain since the system has switched to your swim speed which ignores the effects of Water difficult terrain.

I'm open to changing the way this works if you've got suggestions.

**Comment by zarmstrong** [comment]
- Ok, thanks, I understand the intent now and agree there must be a way to distinguish between the two. That said, I don't think aquatic is the right word; there's no reason I would assume they behave differently based on the definition of aquatic. Perhaps "moving water"/"flowing water" or "water with current" would be a better way to describe it. I'm pulling those terms from the CRB: https://2e.aonprd.com/Rules.aspx?ID=593. I assume these terms aren't coming from this module though, and are coming from ETL. I'll raise this issue there.

**Comment by velara** [comment]
I can define the environment list myself using an override and in fact aquatic is one of the terms I added based on the rangers list of favoured environments they can choose. Hmm. Current is indeed a clearer way of expressing its purpose.

I’ll add that. I think fundamentally I need to talk to iron monk about distinguishing between environment and obstacle. But have clearer names will help for sure

I’ve got an idea bouncing around my head for how to do so.

**Comment by zarmstrong** [comment]
Yeah, I figured you were using the list from favored terrain/terrain expertise and the like, so keeping aquatic makes sense. Maybe Aquatic (calm) vs Aquatic (flowing/rough).   I agree that keeping the terms for the terrains as listed in the book makes the most sense. Hopefully in the future you can even check if the PC has that favored terrain and remove the difficulty from it. You'd probably want a flag on the terrain (magical/mundane) for the purposes of that, though.

**Comment by velara** [comment]
I'm working on a pull request for enhanced terrain layer that will add obstacle types. Which should hopefully resolve some of the confusion. If it gets accepted, you'd be able to set the terrain's environment. Ex. Coast and the obstacle type, for example Water. 

Eventually the plan is to integrate more closely with the PF2e system such that feats and the like will have rule elements that automatically handle ignore mundane difficult terrain for rangers for example.

However, at present if you've got a ranger and you give them the Reduce Non-Magical effect from the Movement Effects compendium they will ignore all difficult terrain and reduce greater difficult terrain to difficult terrain for all terrain that does not have its environment sent to magical.

**Comment by zarmstrong** [comment]
Awesome, thanks for the great module and contributing on the ETL module too

**Comment by velara** [comment]
Obstacles, which are now part of ETL should help alleviate some of the confusion.
